ALTER TABLE venues
ADD COLUMN IF NOT EXISTS category VARCHAR(100),
ADD COLUMN IF NOT EXISTS district VARCHAR(100),
ADD COLUMN IF NOT EXISTS rating NUMERIC(3,1) DEFAULT 4.5,
ADD COLUMN IF NOT EXISTS review_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS image_url TEXT,
ADD COLUMN IF NOT EXISTS amenities TEXT;

INSERT INTO venues (name, category, description, address, district, max_capacity, reference_price, rating, review_count, image_url, amenities) VALUES
('Hacienda Sabandía', 'Boda', 'Hermosa hacienda tradicional rodeada de vegetación y arquitectura colonial, ideal para bodas campestres inolvidables.', 'Av. Sabandía s/n', 'Sabandía', 350, 18500.00, 4.9, 142, 'https://www.chullostravelperu.com/blog/wp-content/uploads/2025/11/Molino-abre.jpg', 'Jardines amplios,Estacionamiento privado,Zona de ceremonia,Cocina equipada'),
('Fundo El Fierro', 'Boda', 'Exclusivo local en Yanahuara con ambiente colonial e iluminación cálida para eventos elegantes.', 'Calle Cuesta del Angel 102', 'Yanahuara', 250, 16000.00, 4.8, 118, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/5d/fc/2d/fundo-el-fierro.jpg?w=1200&h=1200&s=1', 'Salón principal,Piscina,Sonido profesional,Seguridad'),
('Casona Tristán del Pozo', 'Empresarial', 'Histórico monumento arquitectónico perfecto para conferencias de gala, lanzamientos de marca y recepciones.', 'Calle San Francisco 115', 'Cercado', 200, 22000.00, 4.7, 85, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0C4Tfy46ncHhNlxUH8lebEnPlEi14zAxpQAGj50OHeuJuJXcp9L1y-7A&s=10', 'Proyector 4K,Audio envolvente,Catering exclusivo,WiFi de alta velocidad'),
('Quinta Los Mangos', 'Quinceañero', 'Espacio moderno con amplias áreas verdes, pista de baile techada y luces audiorítmicas para 15 años.', 'Av. Fernandini 405', 'Sachaca', 280, 13500.00, 4.6, 94, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzvG7kyCc4RMHy4LMSg9MbJ5mUDi8nO1DWe0aky4M_aQ&s=10', 'Pista LED,Jardín,Efectos de luces,Camerino privado'),
('Centro de Convenciones Cerro Juli', 'Empresarial', 'El centro ferial más grande del sur del país, apto para congresos masivos, exposiciones y cenas corporativas.', 'Av. Cerro Juli s/n', 'José Luis Bustamante', 1500, 45000.00, 4.8, 210, 'https://larepublica.cronosmedia.glr.pe/original/2024/09/20/66edf1744d91182fc67e459f.jpg', 'Estacionamiento masivo,Traducción simultánea,Climatización,Escenario modular'),
('Villa Los Arcos', 'Boda', 'Elegante villa de arquitectura arequipeña con arcos de sillar y vista directa al Misti.', 'Av. Aviación 120', 'Yanahuara', 300, 20000.00, 4.9, 130, 'https://agavevillas.com/wp-content/uploads/2025/11/1678737805.jpg', 'Vista al Misti,Capilla privada,Salón con sillar,Bar amoblado'),
('Jardines de Cayma', 'Quinceañero', 'Local acogedor en el corazón de Cayma con bellas fuentes de agua y vegetación cuidada.', 'Av. Cayma 510', 'Cayma', 220, 12000.00, 4.5, 76, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPuTi9NYXzzARm6Fc8HTK21-QVUmRkedvapRZcuyYK6A&s=10', 'Fuentes iluminadas,Zona de fotos,Seguridad 24h,Cocina auxiliar'),
('Palacio Metropolitano de Bellas Artes', 'Empresarial', 'Moderna infraestructura cultural ideal para simposios, premiaciones y ceremonias de gran nivel.', 'Av. Parra 204', 'Cercado', 800, 30000.00, 4.7, 115, 'https://diarioelpueblo.com.pe/wp-content/uploads/2023/06/11-.jpg', 'Auditorio acústico,Cámaras de seguridad,Accesibilidad universal,Cabina de prensa'),
('Hacienda Los Bustamante', 'Boda', 'Tradicional fundo campestre con extensas áreas verdes e instalaciones rústicas confortables.', 'Panamericana Sur Km 8', 'Tiabaya', 400, 17500.00, 4.8, 89, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6pfPFfIB_pLROEhlWOEVYsbEMJY_43bPA1EaOeymEMJTA_x9qLEbU0t-R&s=10', 'Cancha de grass natural,Estacionamiento amplio,Espacio para toldos,Generador eléctrico'),
('Salón Real Arequipa', 'Quinceañero', 'Salón de eventos de 2 niveles con terminados lujosos, candelabros y sistema de sonido integrado.', 'Av. Ejército 840', 'Cerro Colorado', 350, 15000.00, 4.6, 102, 'https://lafabricadeeventos.com/img/utils/Hero.jpg', 'Ascensor,Aire acondicionado,Escenario alto,Baños de lujo'),
('Villa El Campestre', 'Social', 'Local campestre para aniversarios, almuerzos de integración y celebraciones familiares.', 'Av. Characato 302', 'Characato', 250, 9500.00, 4.4, 63, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8_PW2eiFC5Q0ZGWwNiNoBpgC_79QfQm_hiWkTYbkMTBzzskzXcWXVaisY&s=10', 'Zona de parrilla,Juegos infantiles,Piscina templada,Gazeebos'),
('La Casona del Sol', 'Social', 'Encantadora casona rodeada de parques naturales y clima fresco durante todo el año.', 'Calle Los Arboles 150', 'Selva Alegre', 180, 11000.00, 4.6, 70, 'https://cdn0.bodas.com.mx/vendor/1013/3_2/1280/jpg/casona-1_5_111013.jpeg', 'Terraza panorámica,Chimea exterior,Bar rústico,Wifi 5G'),
('Terraza Misti Sunset', 'Social', 'Terraza rooftop exclusiva con vista panorámica a la ciudad y a los volcanes Misti y Chachani.', 'Calle Bolivar 300', 'Yanahuara', 150, 14000.00, 4.9, 155, 'https://cache.marriott.com/content/dam/marriott-renditions/LIMWI/limwi-ballroom-dance-floor-9195-hor-clsc.jpg?output-quality=70&interpolation=progressive-bilinear&downsize=1200px:*', 'Vista a los volcanes,Barra de coctelería,Lounge interior,Calefacción outdoor'),
('Fundo San José', 'Boda', 'Majestuoso fundo con arboledas centenarias para recepciones campestres al aire libre.', 'Av. Socabaya 890', 'Socabaya', 500, 21000.00, 4.8, 97, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcOm2UQSrhSWpHclzQU64-Futqv5msPaaNL9YskDenFT6q57gvMR_NjNnJ&s=10', 'Pista asfaltada,Toldo gigante,Camerinos novios,Seguridad privada'),
('Club de Tiro Bellavista', 'Empresarial', 'Amplias instalaciones corporativas y deportivas para aniversarios de empresa y teambuildings.', 'Calle Ugarteche 210', 'Yanahuara', 600, 19000.00, 4.7, 110, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRY9rRSpOixRBamk8H_6NegSOXCuArbit4xgUZxITeCS71aTm-1fBKwRDI&s=10', 'Salón de gala,Canchas sintéticas,Amplia explanada,Catering interno');
