ALTER TABLE events
ADD COLUMN name VARCHAR(255),
ADD COLUMN description TEXT,
ADD COLUMN location VARCHAR(255),
ADD COLUMN status VARCHAR(50),
ADD COLUMN budget DECIMAL(10,2),
ADD COLUMN budget_used DECIMAL(10,2),
ADD COLUMN cover_image TEXT;
